language: node_js
node_js:
  - "8.7"

branches:
  only:
    - master

before_script:
  - chmod 600 .travis/prepare-env.sh
  - .travis/prepare-env.sh
  - npm install -g @angular/cli

script:
  - cd client
  - ng build --prod

after_success:
  - chmod 600 .travis/push.sh
  - .travis/push.sh

notifications:
  email:
    on_failure: change
    on_success: change