language: node_js
node_js:
  - "8.7"

branches:
  only:
    - master

before_script:
  - chmod 777 .travis/prepare-env.sh
  - .travis/prepare-env.sh
  - npm install -g @angular/cli

script:
  - cd client
  - npm install
  - ng build --prod

after_success:
  - chmod 777 .travis/push.sh
  - .travis/push.sh

#cache:
#  directories:
#    - "node_modules"
#    - "client/node_modules"
#    - "server/node_modules"

notifications:
  email:
    on_failure: change
    on_success: change